on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init NodeJS
        uses: ./.github/actions/setup-github-actions-node

      - name: Compute backport targets
        id: targets
        run: node .github/scripts/compute-backport-targets.mjs

      - name: Backport
        if: steps.targets.outputs.target_branches != ''
        uses: korthout/backport-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_pr_number: ${{ github.event.pull_request.number }}
          target_branches: ${{ steps.targets.outputs.target_branches }}
          pull_description: |-
            # Description
            Backport of #${pull_number} to `${target_branch}`

            # Original description

            ${pull_description}
          pull_title: ${pull_title} (backport to ${target_branch})
          add_author_as_assignee: true
          copy_assignees: true
          copy_requested_reviewers: true
          copy_labels_pattern: '^(?!Backport to\b).+' # Copy everything except backport labels
          experimental: >
            {
              "conflict_resolution": "draft_commit_conflicts"
            }
